# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.64.3'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class InventoryServiceStub(object):
    """InventoryService stellt Operationen zur Prüfung und Reservierung von Artikelbeständen bereit.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAndReserve = channel.unary_unary(
                '/shop.inventory.v1.InventoryService/CheckAndReserve',
                request_serializer=inventory__pb2.ReservationRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReservationResponse.FromString,
                _registered_method=True)
        self.ReleaseReservation = channel.unary_unary(
                '/shop.inventory.v1.InventoryService/ReleaseReservation',
                request_serializer=inventory__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReleaseResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """InventoryService stellt Operationen zur Prüfung und Reservierung von Artikelbeständen bereit.
    """

    def CheckAndReserve(self, request, context):
        """Prüft, ob alle Artikel verfügbar sind und reserviert sie bei Erfolg.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseReservation(self, request, context):
        """Hebt eine zuvor vorgenommene Reservierung wieder auf.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAndReserve': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAndReserve,
                    request_deserializer=inventory__pb2.ReservationRequest.FromString,
                    response_serializer=inventory__pb2.ReservationResponse.SerializeToString,
            ),
            'ReleaseReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseReservation,
                    request_deserializer=inventory__pb2.ReleaseRequest.FromString,
                    response_serializer=inventory__pb2.ReleaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.inventory.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shop.inventory.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """InventoryService stellt Operationen zur Prüfung und Reservierung von Artikelbeständen bereit.
    """

    @staticmethod
    def CheckAndReserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.inventory.v1.InventoryService/CheckAndReserve',
            inventory__pb2.ReservationRequest.SerializeToString,
            inventory__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.inventory.v1.InventoryService/ReleaseReservation',
            inventory__pb2.ReleaseRequest.SerializeToString,
            inventory__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
