# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x11shop.inventory.v1\"t\n\x12ReservationRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.shop.inventory.v1.OrderItem\x12\x1f\n\x17reservation_ttl_seconds\x18\x03 \x01(\x05\"1\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xc5\x01\n\x13ReservationResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x34\n\x06status\x18\x02 \x01(\x0e\x32$.shop.inventory.v1.ReservationStatus\x12\x16\n\x0ereservation_id\x18\x03 \x01(\t\x12=\n\x11unavailable_items\x18\x04 \x03(\x0b\x32\".shop.inventory.v1.UnavailableItem\x12\x0f\n\x07message\x18\x05 \x01(\t\"K\n\x0fUnavailableItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x11\n\trequested\x18\x02 \x01(\x05\x12\x11\n\tavailable\x18\x03 \x01(\x05\":\n\x0eReleaseRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\"K\n\x0fReleaseResponse\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t*\xa9\x01\n\x11ReservationStatus\x12\"\n\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12 \n\x1cRESERVATION_STATUS_CONFIRMED\x10\x01\x12*\n&RESERVATION_STATUS_PARTIALLY_AVAILABLE\x10\x02\x12\"\n\x1eRESERVATION_STATUS_UNAVAILABLE\x10\x03\x32\xd1\x01\n\x10InventoryService\x12`\n\x0f\x43heckAndReserve\x12%.shop.inventory.v1.ReservationRequest\x1a&.shop.inventory.v1.ReservationResponse\x12[\n\x12ReleaseReservation\x12!.shop.inventory.v1.ReleaseRequest\x1a\".shop.inventory.v1.ReleaseResponseBR\n\x17\x63om.shopag.inventory.v1P\x01Z5github.com/shop-ag/inventory-service/gen/go;inventoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.shopag.inventory.v1P\001Z5github.com/shop-ag/inventory-service/gen/go;inventory'
  _globals['_RESERVATIONSTATUS']._serialized_start=622
  _globals['_RESERVATIONSTATUS']._serialized_end=791
  _globals['_RESERVATIONREQUEST']._serialized_start=38
  _globals['_RESERVATIONREQUEST']._serialized_end=154
  _globals['_ORDERITEM']._serialized_start=156
  _globals['_ORDERITEM']._serialized_end=205
  _globals['_RESERVATIONRESPONSE']._serialized_start=208
  _globals['_RESERVATIONRESPONSE']._serialized_end=405
  _globals['_UNAVAILABLEITEM']._serialized_start=407
  _globals['_UNAVAILABLEITEM']._serialized_end=482
  _globals['_RELEASEREQUEST']._serialized_start=484
  _globals['_RELEASEREQUEST']._serialized_end=542
  _globals['_RELEASERESPONSE']._serialized_start=544
  _globals['_RELEASERESPONSE']._serialized_end=619
  _globals['_INVENTORYSERVICE']._serialized_start=794
  _globals['_INVENTORYSERVICE']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
